---
title: "Forecasting Dashboard - Manual"
author: "Marco Zanotti"
format: html
toc: true
---

The time series forecasting dashboard is a tool to help you forecast the future 
values of a time series. The dashboard is designed to be used by people who may
not be familiar with time series forecasting techniques.  

The dashboard provides a simple interface to:  

- upload the time series  
- visualize, impute missing values and transform data  
- detect and clean anomalies  
- perform hypothesis testing  
- create and select features  
- test and evaluate different forecasting models  
- compare the performance of different models  
- optimize the models  
- explain the models forecasts  
- combine the model forecasts  
- perform scenario analysis.  



## Section 1: Data

The Data section is where you upload the time series data. The data should be
in a CSV file containing columns 'date', 'id', 'frequency' and 'value'.  



## Section 2: Analyze

The Analyze section is where you perform the initial analysis of the time series
data. This includes visualizing the data, imputing missing values, transforming
the data, detecting and cleaning anomalies, and performing hypothesis testing.  

### Visualize & Transform

### Anomaly Detection & Cleaning

### Hypothesis Testing



## Section 3: Feature Engineering

The Feature Engineering section is where you create and select features for the
forecasting models.  


## Section 4: Forecast

The Forecast section is where you test and evaluate different forecasting models.
You can compare the performance of different models, optimize the models, explain
the models forecasts, combine the model forecasts, and perform scenario analysis.  

### Test & Evaluate

### Compare

### Optimize

### Explain

### Combine

### Scenario Analysis


